server:
  servlet:
    encoding:
      force-response: true
spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    open-in-view: false
#  data:
#    web:
#      pageable:
#        one-indexed-parameters: true
#        default-page-size: 5