server:
  servlet:
    encoding:
      force-response: true

spring:
  datasource:
    url: jdbc:h2:mem:testdb;NON_KEYWORDS=USER
    username: ENC(Wud39EfWmpiuTtA/+nJhsA==)
    password:
    path: /h2-console
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        ddl-auto: create-drop
        show_sql: true
        format_sql: true
        logging.level:
        org.hibernate.SQL: debug
    defer-datasource-initialization: true

  sql:
    init.mode: never # data.sql 실행 여부
jwt:
  secret: "Q3zTqhZVcfl17cKZzBbeQVZ41AAuthQYcCWEPLrVm+8="
  expiration: 86400000 # 1 day

