
### 게시글 작성

POST http://localhost:8080/api/posts
Content-Type: application/json

{
  "title": "제목",
  "content": "내용"
}

### 게시글삭제

DELETE http://localhost:8080/api/posts/3
Content-Type: application/json

